### ISSUE TITLE
eac not work

### ISSUE THREAD

**Issue by Exotikcheatt** [4l3x777/dse_pg_bypass#1]
![320245760-03ad9779-5419-4db8-8008-58db1503bc16](https://github.com/4l3x777/dse_pg_bypass/assets/151665701/2d7ac6a0-64a2-4853-84c7-39ac8475e25b)

**Comment by 4l3x777** [comment]
Hi! I don't understand your question about EAC, could you write in more detail what doesn't work?
I tested the patch on the latest win11 and it works correctly with projects such as kdapper, Kaspersky Book, etc. 
I also loaded various unsigned drivers and everything works!

**Comment by Exotikcheatt** [comment]
nah its work my bad i just "repair anticheat"
but what exactly is the DSE for ? I SC start my drive with my signed public cert thanks to DSE but I ate a ban so basically what does it consist of

**Comment by 4l3x777** [comment]
DSE is the OS protection of loading drivers that are unsigned or have a revoked signature certificate. 
If you want to run driver with a self-signed certificate, then you need to add it to the trusted certificates directory and set the testsigning parameter to on.
