### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by TitanCheat** [4l3x777/dse_pg_bypass#2]
In windows 11, after changing eprocess I'm getting bsod: Critical structure corruption 
It's not patching patchguard.

**Comment by 4l3x777** [comment]
Perhaps the problem is that you are destroying the structure so that it loses its correctness! Also, do not forget about other kernel threads that are running at the current time!

**Comment by TitanCheat** [comment]
> Perhaps the problem is that you are destroying the structure so that it loses its correctness! Also, do not forget about other kernel threads that are running at the current time!

Isn't that porpose of patching PG? So I can patch the kernel
If not, what else can I do with your PG bypass that normally I can't?

**Comment by 4l3x777** [comment]
I don't know what you doing in kernel, I patched some field in process in the kernel and it didn't cause any critical errors. WinDdg help you to debugging you problem, good luck!
